name: Streamlit Keep Alive

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  ping_and_verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check App Content
        run: |
          # On télécharge le contenu de la page
          # On cherche le mot "Sleep" ou "Quality" (présents dans ton titre)
          curl -sL https://sleepquality-gpa.streamlit.app/ | grep -qi "Sleep"
          
          if [ $? -eq 0 ]; then
            echo "✅ L'application est bien en ligne et accessible !"
          else
            echo "❌ L'application ne répond pas ou le contenu est bloqué."
            exit 1
          fi
