name: Streamlit Force Wakeup

on:
  schedule:
    - cron: '0 */6 * * *'  
  workflow_dispatch:      # Pour le lancer à la main

jobs:
  push_commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # Important pour le push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Force Push Empty Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Keep alive ping"
          git push
